services/threatexchange/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^query/$', views.query, name='threatexchange-views-query'),
    url(r'^privacy_groups/$', views.privacy_groups, name='threatexchange-views-privacy_groups'),
    url(r'^submit_query/$', views.submit_query, name='threatexchange-views-submit_query'),
    url(r'^submit_related_query/$', views.submit_related_query, name='threatexchange-views-submit_related_query'),
    url(r'^export_object/$', views.export_object, name='threatexchange-views-export_object'),
    url(r'^import_object/$', views.import_object, name='threatexchange-views-import_object'),
    url(r'^get_members/$', views.get_members, name='threatexchange-views-get_members'),
    url(r'^get_groups/$', views.get_groups, name='threatexchange-views-get_groups'),
    url(r'^get_dropdowns/$', views.get_dropdowns, name='threatexchange-views-get_dropdowns'),
    url(r'^get_privacy_group_form/$', views.get_privacy_group_form, name='threatexchange-views-get_privacy_group_form'),
    url(r'^add_edit_privacy_group/$', views.add_edit_privacy_group, name='threatexchange-views-add_edit_privacy_group'),
]

services/threatexchange/forms.py
from django import forms

class ThreatExchangeConfigForm(forms.Form):
    error_css_class = 'error'
    required_css_class = 'required'
    app_id = forms.CharField(required=True,
                             label="App ID",
                             initial='',
                             widget=forms.TextInput(),
                             help_text="Facebook ThreatExchange App ID.")
    app_secret = forms.CharField(required=True,
                             label="App Secret",
                             initial='',
                             widget=forms.PasswordInput(),
                             help_text="Facebook ThreatExchange App Secret.")
    headers = forms.CharField(required=False,
                              label="Headers",
                              initial='',
                              widget=forms.TextInput(),
                              help_text="Custom headers for requests.")
    verify = forms.BooleanField(required=False,
                                label="Verify",
                                initial=False,
                                help_text="Verify requests.")

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', ':')
        super(ThreatExchangeConfigForm, self).__init__(*args, **kwargs)

class ThreatExchangePrivacyGroupForm(forms.Form):
    error_css_class = 'error'
    required_css_class = 'required'
    name = forms.CharField(required=True,
                           label="Name",
                           initial='',
                           widget=forms.TextInput(),
                           help_text="Privacy Group Name.")
    description = forms.CharField(required=True,
                             label="Description",
                             initial='',
                              widget=forms.Textarea(
                                    attrs={'cols': '40', 'rows': '3'}),
                             help_text="Privacy Group Description.")
    members = forms.CharField(required=True,
                              label="Members",
                              initial='',
                              widget=forms.Textarea(
                                    attrs={'cols': '40', 'rows': '3'}),
                              help_text="Comma-separated list of member IDs.")
    members_can_see = forms.BooleanField(required=False,
                                label="Members Can See",
                                initial=False,
                                help_text="Members can see this group.")
    members_can_use = forms.BooleanField(required=False,
                                label="Members Can Use",
                                initial=False,
                                help_text="Members can use this group.")

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', ':')
        super(ThreatExchangePrivacyGroupForm, self).__init__(*args, **kwargs)

services/threatexchange/templates/privacy_form.html
<div id="add_edit_privacy_group" title="Add/Edit Privacy Group">
    <div id="form_privacy_member_list" style="float: right;">
    </div>
    <form id="form-add-edit-privacy-group" 
	  action='{% url "threatexchange-views-add_edit_privacy_group" %}' 
	  method='POST' enctype="multipart/form-data" 
      data-id="">
        <table class="form" width="400px">
            {{privacy_group_form.as_table }}
        </table>
    </form>
    <div id="add_edit_privacy_group_results">
    </div>
</div>

services/threatexchange/templates/privacy_groups.html
{% extends "base.html" %}

{% block title %}ThreatExchange Privacy Groups{% endblock %}

{% block content %}

<style>
    .modify_group {
        font-weight: bold;
        color: #3366ff;
        cursor: pointer;
    }
    .threatexchange_members {
        min-width: 250px;
        max-height: 300px;
        overflow-y: auto;
    }
    .threatexchange_groups {
        width: 100%;
        max-height: auto;
        overflow-y: auto;
    }
    #tx_type_warn {
        display: inline-block;
    }
    #tx_threat_type_warn {
        display: inline-block;
    }
</style>
<div id="threatexchange_privacy_groups" width="100%">
    <div class='threatexchange_members content_box content_details' style="display: none;">
        <h3 class="titleheader">
            <span>Members</span>
        </h3>
        <div id="member_content">
        </div>
    </div>
    <div class='threatexchange_groups content_box content_details'>
        <h3 class="titleheader">
            <span>Owned Groups</span>
            <span class="add_button" id="add_tx_privacy_group">
                <a href="#" class="ui-icon ui-icon-plusthick"></a>
            </span>
        </h3>
        <div>
            <table class="chart">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Members</th>
                        <th>Members Can See</th>
                        <th>Members Can Use</th>
                    </tr>
                </thead>
                <tbody id="owner_group_content">
                </tbody>
            </table>
        </div>
    </div>
    <div class='threatexchange_groups content_box content_details'>
        <h3 class="titleheader">
            <span>Member Groups</span>
        </h3>
        <div>
            <table class="chart">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Members</th>
                        <th>Members Can See</th>
                        <th>Members Can Use</th>
                    </tr>
                </thead>
                <tbody id="member_group_content">
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
function get_members() {
    $.ajax({
        type: "POST",
        url: "{% url 'threatexchange-views-get_members' %}",
        success: function(data) {
            if (data.success) {
                $('#member_content').append(data.html);
            }
        }
    });
}
function get_groups() {
    $.ajax({
        type: "POST",
        data: {'manage': "yes"},
        url: "{% url 'threatexchange-views-get_groups' %}",
        success: function(data) {
            if (data.success) {
                $('#owner_group_content').html('');
                $('#member_group_content').html('');
                $('#owner_group_content').append(data.owner);
                $('#member_group_content').append(data.member);
            }
        }
    });
}
$(document).ready(function() {
    get_members();
    get_groups();
    function submit_privacy_group(elem) {
        var form = elem.children("form");
        var data = {
            id: form.find('#id_id').val(),
            name: form.find("#id_name").val(),
            description: form.find("#id_description").val(),
            members: form.find("#id_members").val(),
            members_can_see: form.find("#id_members_can_see").prop('checked'),
            members_can_use: form.find("#id_members_can_use").prop('checked'),
        }
        $.ajax({
            type: "POST",
            data: data,
            url: "{% url 'threatexchange-views-add_edit_privacy_group' %}",
            success: function(data) {
                var results = form.closest('div')
                              .children("#add_edit_privacy_group_results");
                results.html('');
                results.append(data.html);
                if (data.success) {
                    get_groups();
                }
            }
        });
    }
    $(document).on('click', '#add_tx_privacy_group', function(e) {
        $.ajax({
            type: "POST",
            url: "{% url 'threatexchange-views-get_privacy_group_form' %}",
            success: function(data) {
                if (data.success) {
                    dialog = $(data.html).dialog({
                      autoOpen: true,
                      height: 425,
                      width: 700,
                      modal: true,
                      buttons: {
                        "Submit": function() {
                            submit_privacy_group(dialog);
                        },
                        Cancel: function() {
                          dialog.dialog( "close" );
                        }
                      },
                      close: function() {
                          dialog.dialog( "close" );
                      }
                    });
                    $(".threatexchange_members").show()
                     .appendTo("#form_privacy_member_list");
                }
            }
        });
    });
    $(document).on('click', '.modify_group', function(e) {
        var id = $(this).data('id');
        var name = $(this).data('name');
        var description = $(this).data('description');
        var can_see = $(this).data('can-see');
        var can_use = $(this).data('can-use');
        var members = '';
        var members_list = $(this).data('members').split(',');
        $.each(members_list, function(i) {
            members += $('span[name="' + members_list[i] + '"]').data('id') + ",";
        });
        $.ajax({
            type: "POST",
            url: "{% url 'threatexchange-views-get_privacy_group_form' %}",
            success: function(data) {
                if (data.success) {
                    dialog = $(data.html).dialog({
                      autoOpen: true,
                      height: 425,
                      width: 700,
                      modal: true,
                      buttons: {
                        "Submit": function() {
                            submit_privacy_group(dialog);
                        },
                        Cancel: function() {
                          dialog.dialog( "close" );
                        }
                      },
                      close: function() {
                          dialog.dialog( "close" );
                      }
                    });
                    $(".threatexchange_members").show()
                     .appendTo("#form_privacy_member_list");
                    var form = $('#form-add-edit-privacy-group');
                    $('<input>').attr({
                        type: 'hidden',
                        id: 'id_id',
                        name: 'id',
                        value: id,
                    }).appendTo(form);
                    form.find("#id_name").val(name);
                    form.find("#id_description").val(description);
                    form.find("#id_members").val(members);
                    if (can_see == "True") {
                        form.find("#id_members_can_see").prop('checked', true);
                    }
                    if (can_use == "True") {
                        form.find("#id_members_can_use").prop('checked', true);
                    }
                }
            }
        });
    });
    $(document).on('click', '.add_privacy_member', function(e) {
        var id = $(this).data('id');
        var members = $(this).closest("#add_edit_privacy_group").children("form")
            .find("textarea[name=members]");
        members.val(members.val() + id + ",");
    });
});
</script>

{% endblock %}

services/threatexchange/templates/threatexchange_export_indicator_tab.html
<style>
    .threatexchange_members {
        max-width: 250px;
        max-height: 300px;
        overflow-y: auto;
        float: right;
    }
    .threatexchange_groups {
        max-width: 250px;
        max-height: 300px;
        overflow-y: auto;
        float: right;
    }
    #tx_type_warn {
        display: inline-block;
    }
</style>
<div id="threatexchange_export" width="50%">
    <div class='threatexchange_members content_box content_details'>
        <h3 class="titleheader">
            <span>Members</span>
        </h3>
        <div id="member_content">
        </div>
    </div>
    <div class='threatexchange_groups content_box content_details'>
        <h3 class="titleheader">
            <span>Groups</span>
        </h3>
        <div id="group_content">
        </div>
    </div>

    <div class='content_box content_details' style="width: 50%;">
        <h3 class="titleheader" width="50%">
            <span>Share this indicator via ThreatExchange</span>
        </h3>
        <div>
            <p>
            Remember to properly set your Privacy Type, Privacy Members, and
            Share Level! Hit the "+" in the areas to the right to automatically
            add that group/member to the Privacy Members list. Documentation can
            be found <a href="https://developers.facebook.com/docs/threat-exchange/" target="new">here</a>.
            </p>
            <table class="export_builder">
                <tr id="indicator_row">
                    <td>
                        Indicator
                    </td>
                    <td>
                        <input type="text" id="tx_indicator" name="tx_indicator" size=25 value="{{indicator.value}}" />
                    </td>
                </tr>
                <tr id="type_row">
                    <td>
                        Type
                    </td>
                    <td>
                        <select id="tx_type" name="tx_type">
                        </select>
                        <span id="tx_type_warn" class="ui-icon ui-icon-alert"
                            title="Indicator type was not a valid Type for ThreatExchange"></span>
                    </td>
                </tr>
                <tr id="description_row">
                    <td>
                        Description
                    </td>
                    <td>
                        <input type="text" id="tx_description" name="tx_description" size=25 value="{{indicator.description}}">
                    </td>
                </tr>
                <tr id="status_row">
                    <td>
                        Status
                    </td>
                    <td>
                        <select id="tx_status" name="tx_status">
                        </select>
                    </td>
                </tr>
                <tr id="confidence_row">
                    <td>
                        Confidence
                    </td>
                    <td>
                        <input type="text" id="tx_confidence" name="tx_confidence" size=5 placeholder="25">
                    </td>
                </tr>
                <tr id="severity_row">
                    <td>
                        Severity
                    </td>
                    <td>
                        <select id="tx_severity" name="tx_severity">
                        </select>
                    </td>
                </tr>
                <tr id="review_status_row">
                    <td>
                        Review Status
                    </td>
                    <td>
                        <select id="tx_review_status" name="tx_review_status">
                        </select>
                    </td>
                </tr>
                <tr id="precision_row">
                    <td>
                        Precision
                    </td>
                    <td>
                        <select id="tx_precision" name="tx_precision">
                        </select>
                    </td>
                </tr>
                <tr id="privacy_type_row">
                    <td>
                        Privacy Type
                    </td>
                    <td>
                        <select id="tx_privacy_type" name="tx_privacy_type">
                        </select>
                    </td>
                </tr>
                <tr id="privacy_members_row">
                    <td>
                        Privacy Members
                    </td>
                    <td>
                        <input type="text" id="tx_privacy_members" name="tx_privacy_members" size=50 placeholder="foo">
                    </td>
                </tr>
                <tr id="share_level_row">
                    <td>
                        Share Level
                    </td>
                    <td>
                        <select id="tx_share_level" name="tx_share_level">
                        </select>
                    </td>
                </tr>
                <tr id="tag_row">
                    <td>
                        Tags
                    </td>
                    <td>
                        <input type="text" id="tx_tags" name="tx_tags" size=50 placeholder="foo">
                    </td>
                </tr>
                <tr>
                    <td>
                        <button id="tx_export_submit" name="submit" type="submit">Submit</button>
                        <span id="tx_export_results" style="display: inline-block;"></span>
                        <span id="tx_export_results_message" style="display: inline-block;"></span>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
<script>
$(document).ready(function() {
    $.ajax({
        type: "POST",
        url: "{% url 'threatexchange-views-get_dropdowns' %}",
        success: function(data) {
            var precision = data.precision;
            var privacy_type = data.privacy_type;
            var review_status = data.review_status;
            var severity = data.severity;
            var share_level = data.share_level;
            var status = data.status;
            var types = data.types;
            var t = "{{ indicator.ind_type }}".toUpperCase().replace(' ', '_');
            var tags = '{{ indicator.threat_types|join:"," }},{{ indicator.attack_types|join:"," }}';
            for (var i=0; i < precision.length; i++) {
                $('#tx_precision').append($('<option>', {
                    value: precision[i],
                    text : precision[i]
                }));
            }
            for (var i=0; i < privacy_type.length; i++) {
                $('#tx_privacy_type').append($('<option>', {
                    value: privacy_type[i],
                    text : privacy_type[i]
                }));
            }
            for (var i=0; i < review_status.length; i++) {
                $('#tx_review_status').append($('<option>', {
                    value: review_status[i],
                    text : review_status[i]
                }));
            }
            for (var i=0; i < severity.length; i++) {
                $('#tx_severity').append($('<option>', {
                    value: severity[i],
                    text : severity[i]
                }));
            }
            for (var i=0; i < share_level.length; i++) {
                $('#tx_share_level').append($('<option>', {
                    value: share_level[i],
                    text : share_level[i]
                }));
            }
            for (var i=0; i < status.length; i++) {
                $('#tx_status').append($('<option>', {
                    value: status[i],
                    text : status[i]
                }));
            }
            for (var i=0; i < types.length; i++) {
                $('#tx_type').append($('<option>', {
                    value: types[i],
                    text : types[i]
                }));
            }
            if ($("#tx_type option[value='" + t + "']").length > 0) {
                $("#tx_type option[value='" + t + "']").prop('selected', true);
                $("#tx_type_warn").hide();
            } else {
                $("#tx_export_submit").prop('disabled', true);
            }
            $("#tx_status").val("UNKNOWN");
            $("#tx_severity").val("UNKNOWN");
            $("#tx_review_status").val("UNKNOWN");
            $("#tx_precision").val("UNKNOWN");
            $("#tx_share_level").val("UNKNOWN");
            $("#tx_tags").val(tags);
            $("#tx_privacy_type").val("HAS_WHITELIST");
            ci = {
                 unknown: 0,
                 benign: 25,
                 low: 50,
                 medium: 75,
                 high: 100
            }
            $("#tx_confidence").val(ci["{{indicator.confidence.rating}}"]);
        }
    });
    $.ajax({
        type: "POST",
        url: "{% url 'threatexchange-views-get_members' %}",
        success: function(data) {
            if (data.success) {
                $('#member_content').append(data.html);
            }
        }
    });
    $.ajax({
        type: "POST",
        url: "{% url 'threatexchange-views-get_groups' %}",
        success: function(data) {
            if (data.success) {
                $('#group_content').append(data.html);
            }
        }
    });
    $(document).on('change', '#tx_type', function(e) {
        $("#tx_export_submit").prop('disabled', false);

    });
    $(document).on('click', '.add_privacy_member', function(e) {
         var id = $(this).data('id');
         $('#tx_privacy_members').val($('#tx_privacy_members').val() + id + ',');
    });
    $(document).on('click', '#tx_export_submit', function(e) {
        var res = $('#tx_export_results');
        data = {
             tlo_type: "Indicator",
             oid: "{{ indicator.id }}",
             indicator: $('#tx_indicator').val(),
             type: $('#tx_type').val(),
             description: $('#tx_description').val(),
             status: $('#tx_status').val(),
             confidence: $('#tx_confidence').val(),
             severity: $('#tx_severity').val(),
             review_status: $('#tx_review_status').val(),
             precision: $('#tx_precision').val(),
             privacy_type: $('#tx_privacy_type').val(),
             privacy_members: $('#tx_privacy_members').val(),
             share_level: $('#tx_share_level').val(),
             tags: $('#tx_tags').val(),
        }
        $.ajax({
             type: "POST",
             url: "{% url 'threatexchange-views-export_object' %}",
             data: data,
             success: function(data) {
                 if (data.success) {
                     res.removeClass('ui-icon-alert');
                     res.addClass("ui-icon").addClass("ui-icon-check").attr("title", "success");
                     $('#tx_export_results_message').text("Graph Object ID for exported object: " + data.results.id);
                 } else {
                     res.addClass("ui-icon").addClass("ui-icon-alert").attr("title", data.message);
                 }
             }
        });
    });
});
</script>

services/threatexchange/templates/threatexchange_nav_items.html
<li class='mmenu_item'>
    <a href="{% url 'threatexchange-views-query' %}">ThreatExchange Query</a>
    <ul class='sub-mmenu'>
        <li class='mmenu_item'>
            <a href="{% url 'threatexchange-views-privacy_groups' %}">Privacy Group Manager</a>
        </li>
    </ul>
</li>

services/threatexchange/templates/tx_common.html
<tr>
    <td class="tlp_{{data.share_level}} share_level">
    </td>
    <td>
        {% include custom_template %}
    </td>
    <td>
        {% if exists %}
            {% if type == 'Threat Descriptors' %}
                <a href="{% url 'crits-core-views-details' 'Indicator' objectid %}" style="display:inline-block; float: right;"><span class="ui-icon ui-icon-alert" title="Object exists already"></span></a>
            {% elif type == 'Threat Indicators' %}
                <a href="{% url 'crits-core-views-details' 'Indicator' objectid %}" style="display:inline-block; float: right;"><span class="ui-icon ui-icon-alert" title="Object exists already"></span></a>
            {% elif type == 'Malware Analyses' %}
                <a href="{% url 'crits-core-views-details' 'Sample' objectid %}" style="display:inline-block; float: right;"><span class="ui-icon ui-icon-alert" title="Object exists already"></span></a>
            {% elif type == 'Malware Families' %}
                <a href="{% url 'crits-core-views-details' 'Backdoor' objectid %}" style="display:inline-block; float: right;"><span class="ui-icon ui-icon-alert" title="Object exists already"></span></a>
            {% endif %}
        {% elif no_import  %}
            <span class="ui-icon ui-icon-alert" title="Not enough data to import" style="display:inline-block; float: right";></span>
        {% endif %}
        {% if type != 'Threat Indicators' and type != 'Malware Families' %}
            <button class="import" name="import" style="float: right;" data-id="{{data.id}}" data-type="{{type}}">Import</button>
            <a href="#" style="display:inline-block; float: right"><span class="import_result"></span></a>
        {% endif %}
        {% if type != 'Threat Descriptors' %}
            <span class="find_related_span">
                <select class="find_related" name="find_related" style="float: right;" data-id="{{data.id}}" data-type="{{type}}">
                    <option>Find Connections...</option>
                    {% if type == 'Threat Indicators' %}
                        <option value="descriptors">Descriptors</option>
                        <option value="malware_analyses">Malware Analyses</option>
                        <option value="related">Related</option>
                    {% elif type == 'Malware Analyses' %}
                        <option value="dropped">Dropped</option>
                        <option value="dropped_by">Dropped By</option>
                        <option value="families">Families</option>
                        <option value="threat_indicators">Threat Indicators</option>
                    {% elif type == 'Malware Families' %}
                        <option value="variants">Variants</option>
                    {% endif %}
                </select>
            </span>
        {% endif %}
    </td>
</tr>

services/threatexchange/templates/tx_group.html
<tr>
    <td>
        <span>{{group.name}}</span>
    </td>
    <td>
        <span class="ui-icon ui-icon-plus add_privacy_member" title="Add to privacy members" data-id="{{group.id}}" name="{{group.name}}"></span>
    </td>
</tr>

services/threatexchange/templates/tx_group_member.html
<tr>
    <td>
        {{group.name}}
    </td>
    <td>
        {{group.description}}
    </td>
    <td>
        {% if group.members %}
            {{group.members}}
        {% else %}
            None
        {% endif %}
    </td>
    <td>
        {% if group.members_can_see %}
            Yes
        {% else %}
            No
        {% endif %}
    </td>
    <td>
        {% if group.members_can_use %}
            Yes
        {% else %}
            No
        {% endif %}
    </td>
</tr>

services/threatexchange/templates/tx_group_owner.html
<tr>
    <td>
        <span class="modify_group" data-id="{{group.id}}" data-name="{{group.name}}" data-description="{{group.description}}" data-members="{{group.members}}" data-can-see="{{group.members_can_see}}" data-can-use="{{group.members_can_use}}" style="float: left;">{{group.name}}</span>
    </td>
    <td>
        {{group.description}}
    </td>
    <td>
        {% if group.members %}
            {{group.members}}
        {% else %}
            None
        {% endif %}
    </td>
    <td>
        {% if group.members_can_see %}
            Yes
        {% else %}
            No
        {% endif %}
    </td>
    <td>
        {% if group.members_can_use %}
            Yes
        {% else %}
            No
        {% endif %}
    </td>
</tr>

services/threatexchange/templates/tx_member.html
<tr>
    <td>
    {% if member.email %}
        <a href="mailto:{{member.email}}">
    {% endif %}
        <span>{{member.name}}</span>
    {% if member.email %}
        </a>
    {% endif %}
    </td>
    <td>
        <span class="ui-icon ui-icon-plus add_privacy_member" title="Add to privacy members" data-id="{{member.id}}" name="{{member.name}}"></span>
    </td>
</tr>

services/threatexchange/templates/tx_threat_descriptor.html
<table>
    <colgroup>
        <col width="450px">
        <col width="300px">
        <col width="350px">
    </colgroup>
    <tr>
        <td>
            <table>
                <colgroup>
                    <col width="100px">
                    <col width="350px">
                </colgroup>
                <tr>
                    <td><b>Indicator:</b></td>
                    <td>{{ data.raw_indicator }}</td>
                </tr>
                <tr>
                    <td><b>Type:</b></td>
                    <td>{{ data.type }}</td>
                </tr>
                <tr>
                    <td><b>Threat Type:</b></td>
                    <td>{{ data.threat_type }}</td>
                </tr>
                <tr>
                    <td><b>Owner:</b></td>
                    <td>{{ data.owner.name }}</td>
                </tr>
            </table>
        </td>
        <td>
            <table>
                <tr>
                    <td><b>Status:</b></td>
                    <td>{{ data.status }}</td>
                </tr>
                <tr>
                    <td><b>Confidence:</b></td>
                    <td>{{ data.confidence }}</td>
                </tr>
                <tr>
                    <td><b>Severity:</b></td>
                    <td>{{ data.severity }}</td>
                </tr>
                <tr>
                    <td><b>Review Status:</b></td>
                    <td>{{ data.review_status }}</td>
                </tr>
            </table>
        </td>
        <td>
            <table>
                <tr>
                    <td><b>Precision:</b></td>
                    <td>{{ data.precision }}</td>
                </tr>
                <tr>
                    <td><b>Added On:</b></td>
                    <td>{{ data.added_on }}</td>
                </tr>
                <tr>
                    <td><b>Last Updated:</b></td>
                    <td>{{ data.last_updated }}</td>
                </tr>
            </table>
        </td>
    </tr>
</table>

services/threatexchange/templates/tx_threat_indicator.html
<table>
    <colgroup>
        <col width="1100px">
    </colgroup>
    <tr>
        <td>
            <table>
                <colgroup>
                    <col width="100px">
                    <col width="350px">
                </colgroup>
                <tr>
                    <td><b>Indicator:</b></td>
                    <td>{{ data.indicator }}</td>
                </tr>
                <tr>
                    <td><b>Type:</b></td>
                    <td>{{ data.type }}</td>
                </tr>
            </table>
        </td>
    </tr>
</table>