services/taxii_service/urls.py
from django.conf.urls import url

from . import views

def register_api(v1_api):
    from taxii_service.api import StandardsResource
    v1_api.register(StandardsResource())

urlpatterns = [
    url(r'^taxii_agent/$', views.taxii_poll, name='taxii_service-views-taxii_poll'),
    url(r'^taxii_agent/import/$', views.import_taxii_data, name='taxii_service-views-import_taxii_data'),
    url(r'^taxii_agent/export/(?P<tid>\S+)$', views.download_taxii_content, name='taxii_service-views-download_taxii_content'),
    url(r'^taxii_agent/saved/$', views.list_saved_polls, name='taxii_service-views-list_saved_polls'),
    url(r'^taxii_agent/preview/(?P<poll_id>[\S.]+)/(?P<page>[\S.]+)/(?P<mult>[\S.]+)/$', views.get_import_preview, name='taxii_service-views-get_import_preview'),
    url(r'^taxii_agent/select/(?P<poll_id>[0-9]+\.[0-9]+)/(?P<select>[01x]*)/$', views.select_deselect_all, name='taxii_service-views-select_deselect_all'),
    url(r'^taxii_agent/select/(?P<block_id>[\S.]+)/(?P<select>[\S.]+)/$', views.select_deselect_block, name='taxii_service-views-select_deselect_block'),
    url(r'^configure/$', views.configure_taxii, name='taxii_service-views-configure_taxii'),
    url(r'^configure/(?P<server>[\w ]+)/$', views.configure_taxii, name='taxii_service-views-configure_taxii'),
    url(r'^get_taxii_config_form/(?P<crits_type>\S+)/(?P<crits_id>\S+)/$', views.get_taxii_config_form, name='taxii_service-views-get_taxii_config_form'),
    url(r'^(?P<crits_type>\S+)/(?P<crits_id>\S+)/$', views.execute_taxii_service, name='taxii_service-views-execute_taxii_service'),
    url(r'^(?P<crits_type>\S+)/(?P<crits_id>\S+)/preview$', views.preview_taxii_service, name='taxii_service-views-preview_taxii_service'),
    url(r'^stix_upload/$', views.stix_upload, name='taxii_service-views-stix_upload'),
]

services/taxii_service/forms.py
# (c) 2013, The MITRE Corporation.  All rights reserved.
# Source code distributed pursuant to license agreement.

from django import forms

from crits.core.user_tools import user_sources, get_user_organization
from crits.core.handlers import get_source_names, collect_objects
from crits.core.class_mapper import class_from_type
from crits.services.handlers import get_config
from crits.vocabulary.indicators import IndicatorCI

from datetime import datetime
from dateutil.tz import tzutc

from . import formats
from . import taxii

def get_taxii_feeds(user_srcs):
    # Avoid options that cause failure: set recipients to intersection of
    # user's sources and the sources that have TAXII feeds configured
    sc = get_config('taxii_service')
    taxii_feeds = []
    try:
        for svr in sc.taxii_servers:
            for fid in sc['taxii_servers'][svr]['feeds']:
                fd = sc['taxii_servers'][svr]['feeds'][fid]
                if fd['source'] in user_srcs:
                    taxii_feeds.append(("%s - %s" % (svr, fid),
                                        "%s - %s" % (svr, fd['feedname'])))
    except (AttributeError, KeyError):
        taxii_feeds = []

    return taxii_feeds

class TAXIISendForm(forms.Form):
    rcpts = forms.MultipleChoiceField(required=False,
                                      label="Recipient",
                                      help_text="Recipient Feeds",
                                      widget=forms.SelectMultiple)

    def __init__(self, username, item, *args, **kwargs):
        """
        Initialize the form.
        Populates form fields based on context object (item) and its related
        items. The way the form fields are populated ensures that only
        STIXifyable / CybOXable options are provided.
        """
        kwargs.setdefault('label_suffix', ':')
        super(TAXIISendForm, self).__init__(*args, **kwargs)
        sc = get_config('taxii_service')
        user_srcs = user_sources(username)
        self.fields['rcpts'].choices = get_taxii_feeds(user_srcs)

        # populate all of the multi choice fields with valid options
        # from the context CRITs object's related items.
        for _type in get_supported_types():
            collected = collect_objects(item._meta['crits_type'], item.id,
                                        1, sc['max_rels'], sc['max_rels'],
                                        [_type], user_srcs, False)
            field = forms.MultipleChoiceField(required=False, label=_type)
            field.choices = filter_and_format_choices(collected, item, _type)
            self.fields[_type] = field

    def get_chosen_relations(self):
        """
        Convert multi choice field selections to a flat array
        of { id, type } dicts.
        """
        data = self.cleaned_data
        chosen = []
        for _type in get_supported_types():
            for item in data.get(_type, []):
              chosen.append({'_id' : item, '_type' : _type})
        return chosen

class TAXIIPollForm(forms.Form):
    feeds = forms.MultipleChoiceField(required=True,
                 label="TAXII Feeds",
                 help_text="Feeds to poll for data",
                 widget=forms.SelectMultiple(attrs={'style':"height:200px;"}))

    import_all = forms.BooleanField(required=False, initial=False,
                            label="Skip preview and import all data into CRITs")

    use_last = forms.BooleanField(required=False, initial=True,
                                  label='Get all messages since last full poll')

    begin = forms.DateTimeField(required=False,
                                label='Exclusive Begin Timestamp',
                                initial = datetime.now(tzutc()))

    end = forms.DateTimeField(required=False,
                              label='Inclusive End Timestamp',
                              initial = datetime.now(tzutc()))

    def __init__(self, username, *args, **kwargs):
        """
        Initialize the form.
        """
        kwargs.setdefault('label_suffix', ':')
        super(TAXIIPollForm, self).__init__(*args, **kwargs)
        sc = get_config('taxii_service')
        user_srcs = user_sources(username)
        self.fields['feeds'].choices = get_taxii_feeds(user_srcs)


def filter_and_format_choices(choice_opts, item, _type):
    """
    Given a list of CRITs options, filter out options matching the given item
    and format those options for display as a choice in a multi-select box.

    :param choice_opts A dict of CRITs objects in (id, json_repr) format
    :param item The item being viewed for TAXII service
    :param _type The type of objects represented in the choice_opts dict
    """

    from .handlers import has_cybox_repr

    ret_opts = [] # return storage array
    item_type = item._meta['crits_type'] # get the type of the subject
    choice_fmt = formats.get_format(_type) # get formatting option for current CRITs type
    ind_crits_type = class_from_type("Indicator")._meta['crits_type']
    for choice in choice_opts:
        obj = choice_opts.get(choice)[1]
        if _type == ind_crits_type and not has_cybox_repr(obj):
            # this indicator can't currently be converted to CybOX, so don't offer as option in UI
            continue
        if item.id != obj.id or item_type != _type:
            # only process if the item isn't the current context crits item
            ret_opts.append((choice, choice_fmt.format(obj).encode('utf-8')))
    return ret_opts

def get_supported_types():
    """
    Get a list of supported types for TAXII service.
    """
    supported_types = ['Certificate',
                       'Domain',
                       'Email',
                       'Indicator',
                       'IP',
                       'PCAP',
                       'RawData',
                       'Sample']
    return supported_types

class TAXIIServiceConfigForm(forms.Form):
    error_css_class = 'error'
    required_css_class = 'required'

    namespace = forms.CharField(required=True,
                  label="Namespace (URI)",
                  initial='http://example.com',
                  widget=forms.TextInput(),
                  help_text="The XML namespace to use in STIX documents.")

    ns_prefix = forms.CharField(required=True,
                  label="Namespace Prefix",
                  initial='example',
                  widget=forms.TextInput(),
                  help_text="The XML namespace prefix to use in STIX IDs.")

    header_events = forms.BooleanField(required=False,
                  label="Pkg Header Events",
                  initial=False,
                  help_text="Create an Event from each STIX package header & relate all items to it.")

    obs_as_ind = forms.BooleanField(required=False,
                  label="Observable as Indicator",
                  initial=False,
                  help_text="Create indicators for all qualifying observables instead of Domain and IP TLOs")

    max_rels = forms.IntegerField(required=True,
                                  label="Maximum Related",
                                  initial=200,
                                  min_value=0,
                                  max_value=5000,
                                  widget=forms.TextInput(),
                                  help_text="The maximum number of related "
                                            "items, of each type, that can "
                                            "be selected for a TAXII message.")

    tserver_attrs = {'size': 10,
                     'style':"height:100px; background-image: none"}
    taxii_servers = forms.ChoiceField(required=False,
                  label="TAXII Servers",
                  initial={},
                  widget=forms.Select(attrs=tserver_attrs))

    def __init__(self, choices=[], *args, **kwargs):
        kwargs.setdefault('label_suffix', ':')
        super(TAXIIServiceConfigForm, self).__init__(*args, **kwargs)
        self.fields['taxii_servers'].choices = choices

class TAXIIServerConfigForm(forms.Form):
    error_css_class = 'error'
    required_css_class = 'required'

    servername = forms.CharField(required=True,
                                 label="Server Name",
                                 initial='',
                                 widget=forms.TextInput(),
                                 help_text="Give this server a name "
                                           "(Letters, Numbers, and Spaces).")

    cur_sname = forms.CharField(required=False,
                                label="Current Server Name",
                                initial='',
                                widget=forms.HiddenInput())

    hostname = forms.CharField(required=True,
                               label="Hostname",
                               initial='',
                               widget=forms.TextInput(),
                               help_text="TAXII server hostname. (Omit URI "
                                         "scheme, e.g. 'http://')")

    https = forms.BooleanField(required=False,
                               label="HTTPS",
                               initial=True,
                               help_text="Connect using HTTPS.")

    port = forms.CharField(required=False,
                           label="Port",
                           initial='',
                           widget=forms.TextInput(),
                           help_text="TAXII server port. "
                                     "Leave blank for default.")

    ppath = forms.CharField(required=True,
                            label="Poll Path",
                            initial='/poll/',
                            widget=forms.TextInput(),
                            help_text="Path used when polling the TAXII server.")

    ipath = forms.CharField(required=True,
                            label="Inbox Path",
                            initial='/inbox/',

services/taxii_service/templates/resources/taxii_agent_jscript_tag.html
<script>
        $(document).ready(function() {

		// cache jQuery references to containers
		var current_state = $("#current_state");
		var view_saved = $("#view_saved");
		var form_ctr = $("#taxii_config_container");
		var result_ctr = $("#results_container");
		var error_ctr = $("#error_container");
		show_hide_timestamps();

	    $("#taxii_submit").click(function() {
			$("#taxii-loader").show();
			if ($("#taxii_config_container").is(":visible")) {
				$("#taxii_config_container").slideToggle();
			}
	    	execute_taxii_service();
		});
		$("#stix_submit").click(function() {
			$("#taxii-loader").show();
			if ($("#taxii_config_container").is(":visible")) {
				$("#taxii_config_container").slideToggle();
			}
			upload_stix_doc();
		});
		$("#view_saved").click(function() {
			$("#taxii-loader").show();
			if ($("#taxii_config_container").is(":visible")) {
				$("#taxii_config_container").slideToggle();
			}
			show_saved_poll_list();
		});
		$(".back_to_cfg ").click(function() {
			show_container("Poll for TAXII Messages", form_ctr);
		});

		function show_hide_timestamps() {
			if ($("#id_use_last").is(":checked")) {
				if ($("#timestamp_container").is(":visible")) {
					$("#timestamp_container").slideToggle();
				}
			}
			else {
				if ($("#timestamp_container").is(":hidden")) {
					$("#timestamp_container").slideToggle();
				}
			}
		}

		$('#id_use_last').click(show_hide_timestamps);

		/*
		* Show only the specified container.
		* Update the page header to the given title.
		*/
		function show_container(title, ctr) {
			current_state.text(title);
			form_ctr[ctr == form_ctr ? "show" : "hide"]();
			result_ctr[ctr == result_ctr ? "show" : "hide"]();
			error_ctr[ctr == error_ctr ? "show" : "hide"]();
			$(".content").scrollTop(0);
		}

	    /*
	     * Send configuration data to server in attempt to send a TAXII message.
	     */
	    function execute_taxii_service() {
			view_saved.prop('hidden', true);
			current_state.text("Processing...");
			$("#taxii-loader").show();
			var form_data = $('#taxii_config_form').serialize();
			$.ajax({
				type: "POST",
				url: "{% url 'taxii_service-views-taxii_poll' %}",
				data: form_data,
				dataType: "json"
			}).done(function(data) { // run on successful request
				if (data.success) { // at least some feeds were successfully processed
					$("#results_container").html(data.html);
					show_container("TAXII Poll Results", result_ctr);
					view_saved.prop('hidden', false);
				} else { // some issue occurred
					error_ctr.children(".taxii_notice").html(data.msg);
					show_container("Problems", error_ctr);
				}
			}).fail(function(data) { // server error
				error_ctr.children(".taxii_notice").text("An unexpected server error occurred - notify an administrator.");
				show_container("Problems", error_ctr);
			}).always(function() {
				$("#taxii-loader").hide();
			});
		}

		function upload_stix_doc() {
			view_saved.prop('hidden', true);
			current_state.text("Processing...");
			$("#taxii-loader").show();
			var form_data = $('#taxii_config_form').serialize();
			var form_data = new FormData($('#taxii_config_form').get(0));
			$.ajax({
				type: "POST",
				contentType: 'multipart/form-data',
				url: "{% url 'taxii_service-views-stix_upload' %}",
				data: form_data,
				dataType: "json",
				processData: false,
				contentType: false
			}).done(function(data) { // run on successful request
				if (data.success) { // at least some feeds were successfully processed
					$("#results_container").html(data.html);
					if (data.imported) {
					    show_container("STIX Import Results", result_ctr);
					} else {
					    show_container("STIX Import Preview", result_ctr);
					}
					view_saved.prop('hidden', false);
				} else { // some issue occurred
					error_ctr.children(".taxii_notice").html(data.msg);
					show_container("Problems", error_ctr);
				}
			}).fail(function(data) { // server error
				error_ctr.children(".taxii_notice").text("An unexpected server error occurred - notify an administrator.");
				show_container("Problems", error_ctr);
			}).always(function() {
				$("#taxii-loader").hide();
			});
		}


		function show_saved_poll_list() {
			view_saved.prop('hidden', true);
			current_state.text("Building List...");
			$("#taxii-loader").show();
			$.ajax({
				type: "GET",
				url: "{% url 'taxii_service-views-list_saved_polls' %}",
			}).done(function(data) { // run on successful request
				if (data.success) { // at least some feeds were successfully processed
					$("#results_container").html(data.html);
					show_container("Saved TAXII Polls & STIX Uploads", result_ctr);
					view_saved.prop('hidden', true);
				} else { // some issue occurred
					error_ctr.children(".taxii_notice").html(data.msg);
					show_container("Problems", error_ctr);
				}
			}).fail(function(data) { // server error
				error_ctr.children(".taxii_notice").text("An unexpected server error occurred - notify an administrator.");
				show_container("Problems", error_ctr);
			}).always(function() {
				$("#taxii-loader").hide();
			});
	    }
	});
</script>

services/taxii_service/templates/resources/taxii_jscript_tag.html
<script>
	$(document).ready(function() {

		// cache jQuery references to containers
		var current_state = $("#current_state");
		var form_ctr = $("#taxii_config_container");
		var result_ctr = $("#results_container");
		var confirm_ctr = $("#confirm_container");
		var error_ctr = $("#error_container");
		var confirm_box = $("#auth_checkbox");
		var continue_btn = $("#confirm_releasability");
	    $.ajax({ // request the TAXII configuration form
			type: "GET",
			url: "{% url 'taxii_service-views-get_taxii_config_form' type item.id %}",
			dataType: "json",
			success: function(data) {
				if (data) {
				    $("#taxii_form_table").html(data.form);
				}
			}
	    });
	    $("#taxii_submit").click(function() {
			$("#taxii-loader").show();
			if ($("#taxii_config_container").is(":visible")) {
				$("#taxii_config_container").slideToggle();
			}
			$("#taxii_configure").text("Show");
	    	execute_taxii_service(false);
		});
		$("#taxii_preview").click(function() {
			open_preview();
		});
		$(".back_to_cfg ").click(function() {
			confirm_box.prop("checked", false);
			show_container("Build TAXII Message", form_ctr);
		});
		continue_btn.click(function() {
			if (confirm_box.is(":checked")) {
				execute_taxii_service(true);
			}
		});


		/*
		* Open STIX content preview for current form selections in new window.
		*/
		function open_preview() {
                        var form = $('#taxii_config_form')[0];
                        form.action = "{% url 'taxii_service-views-preview_taxii_service' type item.id %}";
                        form.method = "post";
                        form.target = "_blank";
                        form.submit();
		}

		/*
		* Show only the specified container.
		* Update the page header to the given title.
		*/
		function show_container(title, ctr) {
			current_state.text(title);
			form_ctr[ctr == form_ctr ? "show" : "hide"]();
			result_ctr[ctr == result_ctr ? "show" : "hide"]();
			confirm_ctr[ctr == confirm_ctr ? "show" : "hide"]();
			error_ctr[ctr == error_ctr ? "show" : "hide"]();
			$(".content").scrollTop(0);
		}

	    /*
	     * Send configuration data to server in attempt to send a TAXII message.
	     */
	    function execute_taxii_service(confirmed) {
			current_state.text("Processing...");
			$("#taxii-loader").show();
			var form_data = $('#taxii_config_form').serialize();
			if (confirmed) {
				form_data += "&updates_confirmed=1";
			}
			$.ajax({
				type: "POST",
				url: "{% url 'taxii_service-views-execute_taxii_service' type item.id %}",
				data: form_data,
				dataType: "json"
			}).done(function(data) { // run on successful request
				if (data.success) { // server attempted to send TAXII messages
					var results = "";
					$.each(data.rcpts, function(index, val) {
						results += "<tr class=\"taxii-success\"><td>" + val + "</td><td>Success</td></tr>";
					});
					$.each(data.failed_rcpts, function(index, val) {
						results += "<tr class=\"taxii-failed\"><td>" 
							+ val[0] 
							+ "</td><td><strong>Failed</strong> - "
							+ val[1]
							+ "</td></tr>"
					});
					$("#result_status_table").html(results);
					show_container("TAXII Results", result_ctr);
				} else if (data.release_changes) { // releasability prevented send
					var new_content = "";
					$.each(data.release_changes, function(key, val) {
						new_content += "<tr><td class='text-left'><strong>" 
									+ val[0] + "</strong>: " + val[2] 
									+ "</td><td>" 
									+ val[3] 
									+ "</td></tr>";
					});
					$("#unreleasable_list tbody").html(new_content);
					show_container("Confirmation Needed", confirm_ctr);
				} else { // some anticipated issue occurred
					error_ctr.children(".taxii_notice").text(data.reason);
					show_container("Problems", error_ctr);
				}
			}).fail(function(data) { // server error
				error_ctr.children(".taxii_notice").text("An unexpected server error occurred - notify an administrator.");
				show_container("Problems", error_ctr);
			}).always(function() {
				$("#taxii-loader").hide();
			});
	    }
	});
</script>

services/taxii_service/templates/resources/taxii_style_tag.html
<style type="text/css" media="screen">
	/* Custom CSS rules for TAXII Service tab content. */

	#taxii_form_table {
		table-layout: fixed;
		text-align: center;
		width: 100%;
	}
	#taxii_form_table select {
		max-width: 100%;
		width: 300px;
		margin-bottom: 10px;
	}
	#taxii_form_table input:not([type="checkbox"]) {
		max-width: 100%;
		width: 300px;
	}
	#taxii_form_table input {
		margin-bottom: 10px;
	}
	#stix_src_fields select {
		margin-bottom: 0px;
	}
	.taxii-table {
		width: 100%;
		border-collapse: collapse;
	}
	.taxii-table thead tr {
		border-bottom: 2px solid rgba(25, 25, 25, .8);
		font-size: 16px;
	}
	.taxii-table tbody tr {
		font-size: 13px;
		border-top: 1px solid rgba(25, 25, 25, .2);
	}
	.taxii-table tbody td {
		padding-top: 5px;
		padding-bottom: 5px;
	}
	.high_priority {
		color: #F30000;
	}
	.taxii-container {
		padding: 25px 5px 25px 5px;
	}
	.taxii_ctype_label {
		font-size: 14px;
	}
	.required {
		color: #3399ff;
	}
	.taxii_btn {
		background-color: rgb(250,250,250);
		color: #121212;
		font-size: 14px;
		padding: 7px 12px;
		border-radius: 3px;
	}
	.taxii_btn:hover {
		background-color: rgb(215,215,215);
	}
	.taxii_btn:hover {
		background-color: rgb(175,175,175);
	}
	.taxii_notice {
		font-size: 16px;
	}
	.limited_ctr {
		width: 50%;
		max-height: 350px;
		margin: 15px auto;
		overflow-y: auto;
		padding: 15px 15px;
		background-color: white;
		border-radius: 5px;
		border: 1px solid rgba(50, 50, 50, .8);
	}
	.taxii-failed {
		background-color: rgba(200, 0, 0, .3);
	}
	.taxii-success {
		background-color: rgba(0, 200, 0, .3);
	}
	.text-left {
		text-align: left;
	}
</style>