services/metacap_service/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^pdml/(?P<pcap_md5>.+?)/$', views.get_pcap_pdml, name='metacap_service-views-get_pcap_pdml'),
    url(r'^tcpdump/get_form/$', views.get_tcpdump_config_form, name='metacap_service-views-get_tcpdump_config_form'),
    url(r'^tcpdump/(?P<pcap_md5>.+?)/$', views.get_pcap_tcpdump, name='metacap_service-views-get_pcap_tcpdump'),
]

services/metacap_service/forms.py
from django import forms

class TCPDumpForm(forms.Form):
    error_css_class = 'error'
    required_css_class = 'required'
    bpf = forms.CharField(required=False,
                          label="BPF Filter",
                          widget=forms.TextInput(),
                          help_text="Filter content to be used in output.")
    sequence = forms.BooleanField(required=False,
                                  label="Absolute Sequence Numbers",
                                  help_text="Use absolute instead of relative sequence numbers.")
    timestamp = forms.ChoiceField(required=False,
                                  widget=forms.Select,
                                  label="Timestamps",
                                  help_text="Timestamp printing on each dump line.")
    verbose = forms.ChoiceField(required=False,
                                  widget=forms.Select,
                                  label="Verbosity",
                                  help_text="How much verbosity you want on output.")
    data = forms.ChoiceField(required=False,
                             widget=forms.Select,
                             label="Data Printing",
                             help_text="Adjust how you want the data of each packet printed.")
    carve = forms.BooleanField(required=False,
                               label="Save Results",
                               help_text="Save resulting PCAP to the database.")

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', ':')
        super(TCPDumpForm, self).__init__(*args, **kwargs)
        self.fields['timestamp'].choices = [("", ""),
                                            ("-t", "(-t) Don't print"),
                                            ("-tt", "(-tt) Print unformatted"),
                                            ("-ttt", "(-ttt) Print delta between current and previous line"),
                                            ("-tttt", "(-tttt) Print in default format proceeded by date"),
                                            ("-ttttt", "(-ttttt) Print delta between current and first line")]
        self.fields['verbose'].choices = [("", ""),
                                          ("-v", "(-v) Verbose"),
                                          ("-vv", "(-vv) More verbose"),
                                          ("-vvv", "(-vvv) Most verbose")]
        self.fields['data'].choices = [("", ""),
                                       ("-A", "(-A) Print ASCII data"),
                                       ("-x", "(-x) Print hex data"),
                                       ("-xx", "(-xx) Print hex data including link level header"),
                                       ("-X", "(-X) Print hex and ascii data"),
                                       ("-XX", "(-XX) Print hex and ascii data including link level header")]

class MetaCapConfigForm(forms.Form):
    error_css_class = 'error'
    required_css_class = 'required'
    basedir = forms.CharField(required=True,
                              label='ChopShop base directory',
                              widget=forms.TextInput(),
                              help_text="The base directory where all the ChopShop modules and libraries exist.",
                              initial='')
    tcpdump = forms.CharField(required=True,
                              label='tcpdump binary',
                              widget=forms.TextInput(),
                              help_text="Full path to the tcpdump binary.",
                              initial='')
    tshark = forms.CharField(required=True,
                              label='tshark binary',
                              widget=forms.TextInput(),
                              help_text="Full path to the tshark binary.",
                              initial='')

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', ':')
        super(MetaCapConfigForm, self).__init__(*args, **kwargs)

services/metacap_service/views.py
import json

from django.conf import settings
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import HttpResponse, render
from django.template.loader import render_to_string

from crits.core.user_tools import user_can_view_data
from . import handlers
from . import forms

@user_passes_test(user_can_view_data)
def get_pcap_pdml(request, pcap_md5):
    if request.method == "GET" and request.is_ajax():
        result = handlers.pcap_pdml_html(pcap_md5, request.user.username)
        if 'objects' in result:
            subscription = {'type': "PCAP", 'id': result['id']}
            object_html = render_to_string('objects_listing_widget.html',
                                           {'objects': result['objects'],
                                            'splunk_search_url': settings.SPLUNK_SEARCH_URL,
                                            'subscription': subscription},
                                           request=request)
            data = {'html': result['html'], 'object_html': object_html}
        else:
            data = {'html': result['html']}
        return HttpResponse(json.dumps(data), content_type="application/json")
    else:
        return render(request, 'error.html', {'error': "Must be AJAX."})

@user_passes_test(user_can_view_data)
def get_pcap_tcpdump(request, pcap_md5):
    if request.method == "POST" and request.is_ajax():
        form = forms.TCPDumpForm(request.POST)
        if form.is_valid():
            data = {'html': handlers.pcap_tcpdump(pcap_md5,
                                                  form,
                                                  request.user.username)}
        else:
            data = {'html': "Invalid form data"}
        return HttpResponse(json.dumps(data), content_type="application/json")
    else:
        return render(request, 'error.html', {'error': "Must be AJAX."})

@user_passes_test(user_can_view_data)
def get_tcpdump_config_form(request):
    if request.method == "GET" and request.is_ajax():
        tcp_form = {'form': forms.TCPDumpForm().as_table()}
        return HttpResponse(json.dumps(tcp_form), content_type="application/json")
    else:
        return render(request, 'error.html', {'error': "Must be AJAX."})

services/metacap_service/templates/metacap_tcpdump_pcap_tab.html
<script>
$(document).ready(function() {
    get_tcpdump_form();
    $("#tcpdump_submit").click(function() {
      $('.tcpdump_loader').html('<img src="/new_images/loader.gif" />');
      var form_data = $('#tcpdump_config_form').serialize();
      $.ajax({
        type: "POST",
        url: "{% url 'metacap_service-views-get_pcap_tcpdump' pcap.md5 %}",
        data: form_data,
        dataType: "json",
        success: function(data) {
          if (data) {
              $("#pcap_tcpdump > pre").text('');
              if ($('#id_carve').is(':checked')) {
                  $("#pcap_tcpdump > pre").html(data['html']);
              } else {
                  $("#pcap_tcpdump > pre").text(data['html']);
              }
              $('.tcpdump_loader').html('');
          }
        }
      });
    });
    $("#tcpdump_configure").click(function() {
        $("#tcpdump_config_container").slideToggle();
    });
    function get_tcpdump_form() {
        $.ajax({
            type: "GET",
            url: "{% url 'metacap_service-views-get_tcpdump_config_form' %}",
            dataType: "json",
            success: function(data) {
                if (data) {
                    $("#tcpdump_form_table").html(data.form);
                }
            }
        });
    }
});
</script>

<div id="metacap_tcpdump" width="100%">

    <span class="horizontal_menu" style="text-align: center;">
        <button class="form_submit_button" id="tcpdump_configure" name="tcpdump_configure">Configure TCPDump</button><br />
        <div id="tcpdump_config_container" style="display: none;">
            <br />
            <div class='content_box content_details' style="width: 100%;">
                <h3 class="titleheader" with="100%">
                    <span>TCPDump Configuration Options (<a href="http://www.tcpdump.org/tcpdump_man.html" style="display: inline-block;"> man page</a>)</span>
                </h3>
                <form id="tcpdump_config_form">
                    <table id="tcpdump_form_table" class="form">
                    </table>
                </form>
            </div>
        </div>
        <button class="form_submit_button" id="tcpdump_submit" name="tcpdump_execute">Run TCPDump</button>
    </span>
    <span class="tcpdump_loader horizontal_menu"></span>

    <div class='content_box content_details' style="width: 100%;">
        <h3 class="titleheader" with="100%">
            <span>PCAP: {{ pcap.filename }}</span>
        </h3>
        <div id="pcap_tcpdump" style="width:100%;max-height:450px;overflow:auto;font-size:120%;">
            <pre>
            </pre>
        </div>
    </div>
</div>

services/metacap_service/templates/metacap_viewer_pcap_tab.html
<script>
$(document).ready(function() {
    $("#get_pdml").click(function() {
      $('.pdml_loader').html('<img src="/new_images/loader.gif" />');
      $.ajax({
        type: "GET",
        url: "{% url 'metacap_service-views-get_pcap_pdml' pcap.md5 %}",
        dataType: "json",
        success: function(data) {
          if (data) {
              $("#pcap_pdml").html(data['html']);
              $('.pdml_loader').html('');
              if (data.object_html) {
                  $('#object_box_container').parent().html(data.object_html);
              }
          }
        }
      });
    });
});
</script>

<div id="metacap_viewer" width="100%">

    <span class="horizontal_menu">
    <ul class="hmenu">
        <li class="right">
            <a href="#" id="get_pdml">View PCAP</a>
        </li>
    </ul>
    </span>
    <span class="pdml_loader horizontal_menu"></span>

    <div class='content_box content_details' style="width: 100%;">
        <h3 class="titleheader" with="100%">
            <span>PCAP: {{ pcap.filename }}</span>
        </h3>
        <div id="pcap_pdml" style="width:100%;max-height:450px;overflow:auto;font-size:150%;"></div>
    </div>
</div>